nguyenhuuloc304/OOS

OOS/OOS.Domain/Categories/Models/Category.cs

New Domain Category

---

OOS/OOS.Domain/Users/Models/User.cs

Create Domain User

---

OOS/OOS.Domain/Orders/Models/Orders.cs
OOS/OOS.Presentation.ApplicationLogic/Order/IOrderBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Order/OrderBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Order/OrderBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.WebAPIs/Controllers/OrderController.cs

Features/task 4 be] api delete order

---

OOS/OOS.Presentation.ApplicationLogic/Products/IProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ProductController.cs

update code edit product, he is seen review code help you

Features/task 4 be] api edit product

---

OOS/OOS.Presentation.ApplicationLogic/Users/IUsersBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/CreateUserRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/CreateUserResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Users/UsersBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Users/UsersBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.WebAPIs/Configs/AutoMapperConfig.cs
OOS/OOS.Presentation.WebAPIs/Controllers/UserController.cs
OOS/OOS.Presentation.WebAPIs/OOS.Presentation.WebAPIs.csproj
OOS/OOS.Presentation.WebAPIs/Startup.cs

Features/task 4 be] api create user

---

OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/ICategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryResponse.cs
OOS/OOS.Presentation.WebAPIs/Controllers/CategoryController.cs
OOS/OOS.Presentation.WebAPIs/OOS.Presentation.WebAPIs.csproj
OOS/OOS.Presentation.WebAPIs/Startup.cs

Features/task 11 be] api delete category

---

OOS/OOS.Presentation.ApplicationLogic/Order/IOrderBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Order/OrderBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/OrderController.cs
OOS/OOS.Presentation.WebAPIs/Startup.cs

Features/task 5 be] api get order

---

OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/ICategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryResponse.cs
OOS/OOS.Presentation.WebAPIs/Configs/AutoMapperConfig.cs
OOS/OOS.Presentation.WebAPIs/Controllers/CategoryController.cs
OOS/OOS.Presentation.WebAPIs/Controllers/UserController.cs
OOS/OOS.Presentation.WebAPIs/OOS.Presentation.WebAPIs.csproj
OOS/OOS.Presentation.WebAPIs/Startup.cs

Features/task 9 be] api create category

---

OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/ICategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/GetCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/GetCategoryResponse.cs
OOS/OOS.Presentation.WebAPIs/Controllers/CategoryController.cs

Features/task 12 be] api get category

---

OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/GetCategoryResponse.cs

edit GetCategoryResponse

---

OOS/OOS.Domain/OOS.Domain.csproj
OOS/OOS.Domain/Orders/Models/Orders.cs
OOS/OOS.Presentation.ApplicationLogic/Order/Messages/CreateOrderResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Order/Messages/EditOrderRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Order/OrderBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/OrderController.cs
OOS/OOS.Presentation.WebAPIs/appsettings.json
OOS/OOS.Shared/Enums/OrderStatus.cs

Features/task 3 be] api edit order

---

OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/EditCategoryResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/CreateUserRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/CreateUserResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/EditUserResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Users/UsersBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Users/UsersBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.WebAPIs/Controllers/CategoryController.cs
OOS/OOS.Presentation.WebAPIs/Controllers/UserController.cs
OOS/OOS.Presentation.WebAPIs/Filters/ValidationFilter.cs
OOS/OOS.Presentation.WebAPIs/Startup.cs

global validation

---

OOS/OOS.Domain/Categories/Models/Category.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/CategoriesBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/ICategoriesBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/EditCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/EditCategoryResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/GetCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/GetCategoryResponse.cs
OOS/OOS.Presentation.WebAPIs/Controllers/CategoryController.cs
OOS/OOS.Shared/Enums/CategoryStatus.cs

please review code for me, sir.

Features/task 28 be] get list categories

---

OOS/OOS.Domain/Products/Models/Product.cs
OOS/OOS.Presentation.ApplicationLogic/Products/IProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/Messages/CheckExistedCodeResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Products/Messages/CreateProductRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ProductController.cs

Create method checkExistedCode
Add filed Code in Product Model

Add file Code in Product Model

---

OOS/OOS.Presentation.WebAPIs/Filters/GlobalExceptionFilter.cs
OOS/OOS.Presentation.WebAPIs/Startup.cs

anh check dùm em.
Cho em hỏi:
return
{
message:
isSuccess:
errorCode:
}
thì isSuccess là luôn luôn false với errorCode là 500 phải không anh

Features/task 17 be] global exception

---

OOS/OOS.Domain/Products/Models/Product.cs
OOS/OOS.Presentation.ApplicationLogic/Order/IOrderBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Order/OrderBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/IProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ProductController.cs

Features/task 16 be] get widget products

---

OOS/OOS.Domain/Products/Models/Product.cs
OOS/OOS.Shared/Enums/ProductStatus.cs

A Lộc review code cho em với , rồi deloy lên azzure giúp em với

update BE enum create product

---

OOS/OOS.Domain/Products/Models/Product.cs
OOS/OOS.Presentation.ApplicationLogic/Products/IProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/Messages/EditProductResponse.cs
OOS/OOS.Presentation.ApplicationLogic/Products/Messages/EditProductResquest.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ProductController.cs

review code cho em voiws deloy giups em a oi

Features/task 9   be edit product

---

OOS/OOS.Presentation.ApplicationLogic/Order/Messages/CreateOrderRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Order/Messages/EditOrderRequest.cs
OOS/OOS.Shared/Enums/OrderStatus.cs

-Add validation attribute
- Update Order Status

update code :

---

OOS/OOS.Domain/Configuration/Models/Configuration.cs
OOS/OOS.Presentation.ApplicationLogic/Configurations/ConfigurationBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Configurations/ConfigurationsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Configurations/IConfigurationsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Configurations/Messages/ConfigurationRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Configurations/Messages/ConfigurationResponse.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ConfigurationController.cs
OOS/OOS.Presentation.WebAPIs/Log_GlobalException.txt
OOS/OOS.Presentation.WebAPIs/Startup.cs
OOS/OOS.Shared/Enums/Currency.cs

add configuration api

---

OOS/OOS.Presentation.ApplicationLogic/Order/Messages/GetOrdersResponse.cs

Features/task 45 be] search order

---

OOS/OOS.Presentation.ApplicationLogic/Products/IProductsBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs

update widget product code

---

OOS/OOS.Presentation.WebAPIs/Models/Manager/ChangePasswordViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/EnableAuthenticatorViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/ExternalLoginsViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/IndexViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/RemoveLoginViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/SetPasswordViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/ShowRecoveryCodesViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/Manager/TwoFactorAuthenticationViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/ExternalLoginViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/ForgotPasswordViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/LoginViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/LoginWith2faViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/LoginWithRecoveryCodeViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/RegisterViewModel.cs
OOS/OOS.Presentation.WebAPIs/Models/User/ResetPasswordViewModel.cs

-update Model View  (LoginViewModel,... etc)

---

OOS/OOS.Presentation.ApplicationLogic/Products/ProductsBusinessLogic.cs

anh review giúp em ạ code [BE] top discount product

Features/be]add one more widget   biggest discount

---

OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/CreateCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Categories/Messages/EditCategoryRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/CreateUserRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Users/Messages/EditUserRequest.cs

up code validation for user and category

---

OOS/OOS.Domain/Contacts/Models/Email.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/EmailBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/EmailBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/IEmailBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ContactController.cs

update code contact, save data feedback

---

OOS/OOS.Presentation.ApplicationLogic/Contacts/EmailBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/IEmailBusinessLogic.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ContactController.cs

update code feedback get {id}

---

OOS/OOS.Presentation.ApplicationLogic/Contacts/EmailBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/EmailBusinessLogicAutoMapper.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/IEmailBusinessLogic.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/Messages/EditFeedBackRequest.cs
OOS/OOS.Presentation.ApplicationLogic/Contacts/Messages/EditFeedBackResponse.cs
OOS/OOS.Presentation.WebAPIs/Controllers/ContactController.cs

anh review giúp em ạ code BE của feedback

Features/task 52 allow administrators can manage customer's request

---

OOS/OOS.Presentation.ApplicationLogic/Users/Messages/GetUserResponse.cs

add user response ID

---

OOS/OOS.Presentation.WebAPIs/Controllers/UserController.cs
OOS/OOS.Presentation.WebAPIs/Models/User/GoogleOAuthResponse.cs

add login via google api

---

OOS/OOS.Domain/Categories/Models/Category.cs

fix bug category
